In [8]:
from simulator.sim3 import *
from exploration.env.func import Experiment, Env
from exploration.random.func import RANDOM
import numpy as np
from codegeneration import generate_instruction_sequence
from simulator.sim3 import print_contention_analysis
import pandas as pd
from exploration.history import History

In [2]:
def shared_ressource2vec(in_,E):
    count_banks = np.histogram(in_['details']['banks'],bins = range(E.num_banks+1))[0]/len(in_['details']['banks'])
    count_rows = np.histogram(in_['details']['rows'],bins = range(E.num_rows+1))[0]/len(in_['details']['banks'])
    ratios_core = np.array([sum(np.array(in_['initiators'])==1)/len(in_['initiators'])])
    conflicts = np.array([1*in_['details']['bank_conflicts'],1*in_['details']['row_conflicts']])
    out = np.concatenate((ratios_core,count_banks,count_rows,conflicts),axis=0)
    dict_ = {'ratio_cores':ratios_core,
             'count_banks':count_banks,
             'count_rows':count_rows,
             'conflicts_bank_row':conflicts}
    return out,dict_

In [3]:
def shared_ressource2vec2(in_,E):
    count_banks = np.histogram(in_['details']['banks'],bins = range(E.num_banks+1))[0]/len(in_['details']['banks'])
    count_rows = np.histogram(in_['details']['rows'],bins = range(E.num_rows+1))[0]/len(in_['details']['banks'])
    ratios_core = np.array([sum(np.array(in_['initiators'])==1)/len(in_['initiators'])])
    conflicts = np.array([1*in_['details']['bank_conflicts'],1*in_['details']['row_conflicts']])
    out = np.concatenate((ratios_core,count_banks,count_rows,conflicts),axis=0)
    return out

In [4]:
p0 = generate_instruction_sequence(50)
p1 = generate_instruction_sequence(50)

In [5]:
N = 201
E =Env(300)
H = History(env=E)
random_explor = RANDOM(N,E,H)

In [6]:
random_explor()

step 0/200
step 200/200


In [21]:
for d_ in H.shared_resource_coords:
    print(H.memory_perf['mutual']['shared_resource_events'][d_['program']])

[{'cycle': 21, 'type': 'DDR_MEMORY_CONTENTION', 'resource': 'DDR_MEMORY', 'initiators': [0, 1], 'details': {'banks': [0, 0], 'rows': [0, 0], 'operations': ['read', 'read'], 'statuses': ['ROW MISS', 'waiting'], 'bank_conflicts': True, 'row_conflicts': False}}]
[{'cycle': 43, 'type': 'DDR_MEMORY_CONTENTION', 'resource': 'DDR_MEMORY', 'initiators': [0, 1], 'details': {'banks': [1, 1], 'rows': [0, 1], 'operations': ['read', 'read'], 'statuses': ['ROW HIT', 'waiting'], 'bank_conflicts': True, 'row_conflicts': True}}]
[{'cycle': 36, 'type': 'DDR_MEMORY_CONTENTION', 'resource': 'DDR_MEMORY', 'initiators': [0, 1], 'details': {'banks': [1, 1], 'rows': [0, 1], 'operations': ['read', 'read'], 'statuses': ['ROW HIT', 'waiting'], 'bank_conflicts': True, 'row_conflicts': True}}]
[{'cycle': 7, 'type': 'L2_CACHE_CONTENTION', 'resource': 'L2_CACHE', 'initiators': [0, 1], 'details': {'set_indices': [0, 3], 'operations': ['read', 'read'], 'addresses': [2, 14]}}, {'cycle': 12, 'type': 'DDR_MEMORY_CONTENTI

In [16]:
H.memory_perf['mutual']['shared_resource_events']

{14: [{'cycle': 0,
   'type': 'L2_CACHE_CONTENTION',
   'resource': 'L2_CACHE',
   'initiators': [0, 1],
   'details': {'set_indices': [2, 2],
    'operations': ['read', 'read'],
    'addresses': [8, 11]}},
  {'cycle': 27,
   'type': 'L2_CACHE_CONTENTION',
   'resource': 'L2_CACHE',
   'initiators': [0, 1],
   'details': {'set_indices': [0, 5],
    'operations': ['read', 'read'],
    'addresses': [1, 21]}}],
 22: [{'cycle': 21,
   'type': 'DDR_MEMORY_CONTENTION',
   'resource': 'DDR_MEMORY',
   'initiators': [0, 1],
   'details': {'banks': [0, 0],
    'rows': [0, 0],
    'operations': ['read', 'read'],
    'statuses': ['ROW MISS', 'waiting'],
    'bank_conflicts': True,
    'row_conflicts': False}}],
 26: [{'cycle': 0,
   'type': 'L2_CACHE_CONTENTION',
   'resource': 'L2_CACHE',
   'initiators': [0, 1],
   'details': {'set_indices': [2, 5],
    'operations': ['read', 'read'],
    'addresses': [8, 20]}}],
 33: [{'cycle': 43,
   'type': 'DDR_MEMORY_CONTENTION',
   'resource': 'DDR_MEMORY

In [14]:
shared_ressource2vec(H.memory_perf['mutual']['shared_resource_events'][186][0],E)

(array([0.66666667, 0.66666667, 0.        , 0.33333333, 0.        ,
        0.66666667, 0.33333333, 1.        , 1.        ]),
 {'ratio_cores': array([0.66666667]),
  'count_banks': array([0.66666667, 0.        , 0.33333333, 0.        ]),
  'count_rows': array([0.66666667, 0.33333333]),
  'conflicts_bank_row': array([1, 1])})

In [9]:
H.as_array()

array([[ 60.,  61.,  83., ...,   1.,   1.,   1.],
       [ 59.,  67.,  68., ...,   1.,   1.,   1.],
       [ 59.,  59., 105., ...,   0.,   1.,   1.],
       ...,
       [ 54.,  55.,  56., ...,   1.,   0.,   1.],
       [ 56.,  57.,  59., ...,   1.,   1.,   1.],
       [ 71.,  73.,  95., ...,   1.,   1.,   1.]], shape=(201, 40))

In [10]:
np.array(H.shared_resource_list).min(axis=0)

array([0.33333333, 0.        , 0.        , 0.        , 0.        ,
       0.33333333, 0.        , 1.        , 0.        ])

In [1]:
np.array(H.shared_resource_list).shape

NameError: name 'np' is not defined

In [12]:
H.as_array().shape

(201, 40)

In [13]:
H.shared_resource_coords

[{'program': 27, 'cycle': 22},
 {'program': 27, 'cycle': 26},
 {'program': 30, 'cycle': 27},
 {'program': 44, 'cycle': 8},
 {'program': 44, 'cycle': 23},
 {'program': 57, 'cycle': 37},
 {'program': 57, 'cycle': 41},
 {'program': 64, 'cycle': 33},
 {'program': 70, 'cycle': 26},
 {'program': 99, 'cycle': 54},
 {'program': 101, 'cycle': 46},
 {'program': 105, 'cycle': 23},
 {'program': 110, 'cycle': 39},
 {'program': 114, 'cycle': 28},
 {'program': 127, 'cycle': 34},
 {'program': 131, 'cycle': 20},
 {'program': 146, 'cycle': 8},
 {'program': 153, 'cycle': 21},
 {'program': 155, 'cycle': 44},
 {'program': 158, 'cycle': 24},
 {'program': 161, 'cycle': 28},
 {'program': 161, 'cycle': 32},
 {'program': 164, 'cycle': 8},
 {'program': 167, 'cycle': 26},
 {'program': 185, 'cycle': 7},
 {'program': 185, 'cycle': 22},
 {'program': 185, 'cycle': 41},
 {'program': 191, 'cycle': 23},
 {'program': 191, 'cycle': 27},
 {'program': 191, 'cycle': 46}]

In [14]:
H.memory_perf['core1'].keys()

dict_keys(['time_core1', 'miss_ratios_detailled', 'miss_ratios_global', 'L1_miss_ratio_core0', 'L1_miss_ratio_core1', 'L2_miss_ratio'])

In [2]:
from exploration.imgep.OptimizationPolicy import OptimizationPolicykNN as OP
from exploration.imgep.goal_generator import GoalGenerator as G
from exploration.imgep.imgep import IMGEP

In [3]:
N = 1000
N_init = 1000
k_values = [1]
num_mutations = 1
periode = 5
min_address_core0 = 0
min_address_core1 = 49
max_address_core0 = 50
max_address_core1 = 100
for segment_method in [True]:
    for k in k_values:
        print('k',k)
        print('segment mixing method', segment_method)
        E =Env(300,num_addr=100)
        H = History(env=E)
        Pi = OP(num_mutations = num_mutations,k=k,
                segment_method=segment_method,
                min_address_core0=min_address_core0,
                max_address_core0=max_address_core0,
                min_address_core1=min_address_core1,
                max_address_core1=max_address_core0)
        goal_generator = G()
        imgep = IMGEP(N,N_init,E,H,goal_generator,Pi, periode = periode,
                      min_address_core0=min_address_core0,
                      max_address_core0=max_address_core0,
                      min_address_core1=min_address_core1,
                      max_address_core1=max_address_core1)
        imgep()
        s = 1 if segment_method else 0
        #H.save_pickle(f'data_explor/imgep_run_{k}_{N}_s_{s}')

k 1
segment mixing method True
step 0/999
step 999/999


In [4]:
H.as_array().shape

(1000, 100)

In [5]:
goal_generator = G()

In [6]:
g = goal_generator(H,100)

moi


In [7]:
Pi(g,H,100)

{'core0': {0: ('write', 2),
  1: ('write', 33),
  3: ('read', 15),
  5: ('read', 21),
  6: ('write', 2),
  10: ('write', 25),
  11: ('read', 28),
  12: ('read', 33),
  14: ('read', 15)},
 'core1': {0: ('read', 51),
  2: ('read', 68),
  7: ('write', 95),
  25: ('write', 49)}}

In [28]:
[random.choice(range(4)) for j in range(20)]

[0, 2, 0, 0, 3, 2, 1, 1, 1, 1, 0, 3, 0, 0, 2, 1, 0, 0, 0, 2]

In [18]:
np.random.randint(1,4,(14,10)).T

array([[3, 3, 1, 2, 3, 1, 1, 1, 3, 1, 2, 1, 2, 3],
       [1, 1, 3, 1, 3, 3, 2, 2, 3, 3, 2, 2, 2, 1],
       [1, 2, 2, 3, 1, 3, 1, 3, 3, 3, 2, 3, 1, 2],
       [3, 3, 3, 3, 2, 2, 3, 2, 1, 2, 2, 2, 3, 3],
       [2, 3, 2, 3, 2, 3, 1, 2, 3, 1, 1, 3, 1, 2],
       [1, 1, 1, 3, 1, 2, 2, 1, 3, 3, 2, 2, 1, 3],
       [3, 3, 1, 2, 2, 3, 1, 3, 3, 3, 3, 3, 2, 3],
       [3, 2, 3, 3, 3, 3, 3, 3, 1, 2, 1, 1, 2, 2],
       [2, 1, 3, 1, 3, 2, 3, 1, 3, 2, 2, 1, 3, 1],
       [2, 3, 1, 1, 3, 1, 3, 1, 1, 2, 3, 2, 2, 2]])

In [10]:
H.shared_resource_coords

[{'program': 5, 'cycle': 25},
 {'program': 5, 'cycle': 28},
 {'program': 9, 'cycle': 33},
 {'program': 9, 'cycle': 37},
 {'program': 14, 'cycle': 56},
 {'program': 17, 'cycle': 65},
 {'program': 18, 'cycle': 69},
 {'program': 21, 'cycle': 35},
 {'program': 22, 'cycle': 21},
 {'program': 24, 'cycle': 35},
 {'program': 27, 'cycle': 22},
 {'program': 31, 'cycle': 24},
 {'program': 32, 'cycle': 17},
 {'program': 32, 'cycle': 32},
 {'program': 32, 'cycle': 51},
 {'program': 32, 'cycle': 55},
 {'program': 32, 'cycle': 59},
 {'program': 34, 'cycle': 38},
 {'program': 35, 'cycle': 29},
 {'program': 36, 'cycle': 6},
 {'program': 37, 'cycle': 40},
 {'program': 38, 'cycle': 15},
 {'program': 40, 'cycle': 63},
 {'program': 48, 'cycle': 26},
 {'program': 48, 'cycle': 41},
 {'program': 50, 'cycle': 67},
 {'program': 52, 'cycle': 29},
 {'program': 53, 'cycle': 33},
 {'program': 55, 'cycle': 33},
 {'program': 60, 'cycle': 55},
 {'program': 60, 'cycle': 70},
 {'program': 69, 'cycle': 62},
 {'program': 